name: GitHub Pages

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-python@v5
      - run: npm ci
      - run: npm run build
      - run: npm ci --prefix examples
      - run: npm run build --prefix examples
      - run: node scripts/update-install-docs.js
      - run: python -m venv venv
      - run: venv/bin/pip install mkdocs-material
      - run: venv/bin/python -m mkdocs build --site-dir docs_out
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './docs_out'
      - uses: actions/deploy-pages@v4
        id: deployment
